import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import 'easymde/dist/easymde.min.css';
import { ToastProvider } from '@radix-ui/react-toast';
import { Toaster } from 'react-hot-toast';
import '@toast-ui/editor/dist/toastui-editor.css';
import PwaInstall from '@/components/PwaInstall';
import IosAddToHome from '@/components/IosAddToHome';

const workSans = localFont({
	src: [
		{
			path: './fonts/WorkSans-Black.ttf',
			weight: '900',
			style: 'normal',
		},
		{
			path: './fonts/WorkSans-ExtraBold.ttf',
			weight: '800',
			style: 'normal',
		},
		{
			path: './fonts/WorkSans-Bold.ttf',
			weight: '700',
			style: 'normal',
		},
		{
			path: './fonts/WorkSans-SemiBold.ttf',
			weight: '600',
			style: 'normal',
		},
		{
			path: './fonts/WorkSans-Medium.ttf',
			weight: '500',
			style: 'normal',
		},
		{
			path: './fonts/WorkSans-Regular.ttf',
			weight: '400',
			style: 'normal',
		},
		{
			path: './fonts/WorkSans-Light.ttf',
			weight: '200',
			style: 'normal',
		},
		{
			path: './fonts/WorkSans-ExtraLight.ttf',
			weight: '100',
			style: 'normal',
		},
	],
	variable: '--font-work-sans',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link
					rel="manifest"
					href="/manifest.json"
				/>
				<meta
					name="theme-color"
					content="#432dd7"
				/>
				<meta
					name="apple-mobile-web-app-capable"
					content="yes"
				/>
				<meta
					name="apple-mobile-web-app-status-bar-style"
					content="default"
				/>
				<link
					rel="apple-touch-icon"
					href="/icon.png"
				/>
				<link
					rel="alternate"
					type="application/rss+xml"
					title="SpecHype Latest Publications"
					href={`${process.env.NEXT_PUBLIC_SITE_URL}/rss.xml`}
				/>
			</head>
			<body className={`${workSans.variable}`}>
				{children}
				<PwaInstall />
				<IosAddToHome />
				<Toaster position="top-right" />
			</body>
		</html>
	);
}
