import type { Metadata } from 'next';
import './globals.css';
import 'easymde/dist/easymde.min.css';
import { Toaster } from 'react-hot-toast';
import '@toast-ui/editor/dist/toastui-editor.css';
import '@toast-ui/editor/dist/theme/toastui-editor-dark.css';
import PwaInstall from '@/components/PwaInstall';
import IosAddToHome from '@/components/IosAddToHome';
import Navbar from '@/components/Navbar';
import { ThemeProvider } from '@/components/theme-provider';
import { Analytics } from '@vercel/analytics/next';
import { SessionProvider } from 'next-auth/react';
import BackToTopButton from '@/components/BackToTopButton';
import Script from 'next/script';
import { auth } from '@/auth';
import { SpeedInsights } from '@vercel/speed-insights/next';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await auth();
	return (
		<html
			lang="en"
			suppressHydrationWarning>
			<head>
				<link
					rel="manifest"
					href="/manifest.json"
				/>
				<meta
					name="theme-color"
					content="#432dd7"
				/>
				<meta
					name="apple-mobile-web-app-capable"
					content="yes"
				/>
				<meta
					name="apple-mobile-web-app-status-bar-style"
					content="default"
				/>
				<link
					rel="apple-touch-icon"
					href="/icon.png"
				/>
				<link
					rel="alternate"
					type="application/rss+xml"
					title="SpecHype Latest Publications"
					href={
						process.env.NEXT_PUBLIC_SITE_URL ?
							`${process.env.NEXT_PUBLIC_SITE_URL}/rss.xml`
						:	'/rss.xml'
					}
				/>
				<link
					rel="prefetch"
					href="/next-page"
				/>
				{/* Google Analytics */}
				<Script
					src="https://www.googletagmanager.com/gtag/js?id=G-4W89XZZ62S"
					strategy="afterInteractive"
				/>
				<Script
					id="gtag-init"
					strategy="afterInteractive">
					{`
						window.dataLayer = window.dataLayer || [];
						function gtag(){dataLayer.push(arguments);}
						gtag('js', new Date());
						gtag('config', 'G-4W89XZZ62S');
					`}
				</Script>
			</head>
			<body>
				<SessionProvider session={session}>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange>
						<Navbar />
						{children}
						<PwaInstall />
						<IosAddToHome />
						<Toaster position="top-right" />
					</ThemeProvider>
				</SessionProvider>
				<BackToTopButton />
				<Analytics />
				<SpeedInsights />
			</body>
		</html>
	);
}
